export enum Rank {
    PRIVATE = "PRIVATE",
    PRIVATE_FIRST_CLASS = "PRIVATE_FIRST_CLASS",
    CORPORAL = "CORPORAL",
    SERGEANT = "SERGEANT",
    STAFF_SERGEANT = "STAFF_SERGEANT",
    SERGEANT_FIRST_CLASS = "SERGEANT_FIRST_CLASS",
    MASTER_SERGEANT = "MASTER_SERGEANT",
    SENIOR_MASTER_SERGEANT = "SENIOR_MASTER_SERGEANT",
    ADVANCED_MASTER_SERGEANT = "ADVANCED_MASTER_SERGEANT",
    CHIEF_WARRANT_OFFICER = "CHIEF_WARRANT_OFFICER",
    SECOND_LIEUTENANT = "SECOND_LIEUTENANT",
    LIEUTENANT = "LIEUTENANT",
    CAPTAIN = "CAPTAIN",
    MAJOR = "MAJOR",
    LIEUTENANT_COLONEL = "LIEUTENANT_COLONEL",
    COLONEL = "COLONEL",
    BRIGADIER_GENERAL = "BRIGADIER_GENERAL",
    MAJOR_GENERAL = "MAJOR_GENERAL",
    CHIEF_OF_STAFF = "CHIEF_OF_STAFF",
}

export enum ServiceType {
    HOVA = "HOVA",
    KEVA = "KEVA",
    MILUIM = "MILUIM",
    EZRAH = "EZRAH",
}

export const endpoint = "http://localhost:4000/";